# Copyright (c) 2020 Dell Inc.
---
galaxy_info:
  author: Dell EMC Networking Engineering
  description: >
       The os10_vrrp role facilitates the configuration of Virtual Router Redundancy Protocol (VRRP) attributes in
       devices running Dell EMC SmartFabric OS10.
  license: GPLv3
  min_ansible_version: 2.9.6

  platforms:
  - name: os10

  galaxy_tags:
    - networking
    - dell
    - dellemc
    - emc
    - os10
